name: Build Linux ARM Binary

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build Linux ARM64 binary
        run: |
          GOOS=linux GOARCH=arm64 go build -o carbonqt-linux-arm64

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: carbonqt-linux-arm64
          path: carbonqt-linux-arm64
